apiVersion: v1
entries:
  rabbitmq:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 3.9.5
    created: "2021-09-06T21:40:10.8100917+03:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source message broker software that implements the Advanced
      Message Queuing Protocol (AMQP)
    digest: ce5c0ab056a4e56e7a1a6cfaa0b4450420d83710d699519bbe1a81e61864e2ff
    home: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
    icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
    keywords:
    - rabbitmq
    - message queue
    - AMQP
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: rabbitmq
    sources:
    - https://github.com/bitnami/bitnami-docker-rabbitmq
    - https://www.rabbitmq.com
    urls:
    - https://euhenimoiseenko.github.io/my-helm-charts/rabbitmq-8.21.0.tgz
    version: 8.21.0
generated: "2021-09-06T21:40:10.8002414+03:00"
